[dev]
  framework = "next"
  command = "npm run dev"

[build]
  command = "npm i --prefix=functions/ && npm run build"
  publish = "out"
  functions = "functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"
